spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: letmein

logging:  
  level:
    com.example.userservice: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        retryer:
          period: 100
          maxPeriod: 1000
          maxAttempts: 3
